// Mocks generated by Mockito 5.4.6 from annotations
// in zodart/test/mocks/constructor_element/constructor_element.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:analyzer/dart/element/element.dart' as _i2;
import 'package:analyzer/dart/element/type.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeConstructorElement_0 extends _i1.SmartFake implements _i2.ConstructorElement {
  _FakeConstructorElement_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeInterfaceElement_1 extends _i1.SmartFake implements _i2.InterfaceElement {
  _FakeInterfaceElement_1(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeConstructorFragment_2 extends _i1.SmartFake implements _i2.ConstructorFragment {
  _FakeConstructorFragment_2(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeInterfaceType_3 extends _i1.SmartFake implements _i3.InterfaceType {
  _FakeInterfaceType_3(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeFunctionType_4 extends _i1.SmartFake implements _i3.FunctionType {
  _FakeFunctionType_4(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeLibraryElement_5 extends _i1.SmartFake implements _i2.LibraryElement {
  _FakeLibraryElement_5(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeElementKind_6 extends _i1.SmartFake implements _i2.ElementKind {
  _FakeElementKind_6(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeMetadata_7 extends _i1.SmartFake implements _i2.Metadata {
  _FakeMetadata_7(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeElement_8 extends _i1.SmartFake implements _i2.Element {
  _FakeElement_8(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [ConstructorElement].
///
/// See the documentation for Mockito's code generation for more information.
class MockConstructorElement extends _i1.Mock implements _i2.ConstructorElement {
  @override
  _i2.ConstructorElement get baseElement =>
      (super.noSuchMethod(
            Invocation.getter(#baseElement),
            returnValue: _FakeConstructorElement_0(
              this,
              Invocation.getter(#baseElement),
            ),
            returnValueForMissingStub: _FakeConstructorElement_0(
              this,
              Invocation.getter(#baseElement),
            ),
          )
          as _i2.ConstructorElement);

  @override
  _i2.InterfaceElement get enclosingElement =>
      (super.noSuchMethod(
            Invocation.getter(#enclosingElement),
            returnValue: _FakeInterfaceElement_1(
              this,
              Invocation.getter(#enclosingElement),
            ),
            returnValueForMissingStub: _FakeInterfaceElement_1(
              this,
              Invocation.getter(#enclosingElement),
            ),
          )
          as _i2.InterfaceElement);

  @override
  _i2.InterfaceElement get enclosingElement2 =>
      (super.noSuchMethod(
            Invocation.getter(#enclosingElement2),
            returnValue: _FakeInterfaceElement_1(
              this,
              Invocation.getter(#enclosingElement2),
            ),
            returnValueForMissingStub: _FakeInterfaceElement_1(
              this,
              Invocation.getter(#enclosingElement2),
            ),
          )
          as _i2.InterfaceElement);

  @override
  _i2.ConstructorFragment get firstFragment =>
      (super.noSuchMethod(
            Invocation.getter(#firstFragment),
            returnValue: _FakeConstructorFragment_2(
              this,
              Invocation.getter(#firstFragment),
            ),
            returnValueForMissingStub: _FakeConstructorFragment_2(
              this,
              Invocation.getter(#firstFragment),
            ),
          )
          as _i2.ConstructorFragment);

  @override
  List<_i2.ConstructorFragment> get fragments =>
      (super.noSuchMethod(
            Invocation.getter(#fragments),
            returnValue: <_i2.ConstructorFragment>[],
            returnValueForMissingStub: <_i2.ConstructorFragment>[],
          )
          as List<_i2.ConstructorFragment>);

  @override
  bool get isConst =>
      (super.noSuchMethod(
            Invocation.getter(#isConst),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isDefaultConstructor =>
      (super.noSuchMethod(
            Invocation.getter(#isDefaultConstructor),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isFactory =>
      (super.noSuchMethod(
            Invocation.getter(#isFactory),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isGenerative =>
      (super.noSuchMethod(
            Invocation.getter(#isGenerative),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.InterfaceType get returnType =>
      (super.noSuchMethod(
            Invocation.getter(#returnType),
            returnValue: _FakeInterfaceType_3(
              this,
              Invocation.getter(#returnType),
            ),
            returnValueForMissingStub: _FakeInterfaceType_3(
              this,
              Invocation.getter(#returnType),
            ),
          )
          as _i3.InterfaceType);

  @override
  bool get hasImplicitReturnType =>
      (super.noSuchMethod(
            Invocation.getter(#hasImplicitReturnType),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isAbstract =>
      (super.noSuchMethod(
            Invocation.getter(#isAbstract),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isExtensionTypeMember =>
      (super.noSuchMethod(
            Invocation.getter(#isExtensionTypeMember),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isExternal =>
      (super.noSuchMethod(
            Invocation.getter(#isExternal),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isStatic =>
      (super.noSuchMethod(
            Invocation.getter(#isStatic),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i2.FormalParameterElement> get formalParameters =>
      (super.noSuchMethod(
            Invocation.getter(#formalParameters),
            returnValue: <_i2.FormalParameterElement>[],
            returnValueForMissingStub: <_i2.FormalParameterElement>[],
          )
          as List<_i2.FormalParameterElement>);

  @override
  _i3.FunctionType get type =>
      (super.noSuchMethod(
            Invocation.getter(#type),
            returnValue: _FakeFunctionType_4(this, Invocation.getter(#type)),
            returnValueForMissingStub: _FakeFunctionType_4(
              this,
              Invocation.getter(#type),
            ),
          )
          as _i3.FunctionType);

  @override
  bool get isSimplyBounded =>
      (super.noSuchMethod(
            Invocation.getter(#isSimplyBounded),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i2.LibraryElement get library =>
      (super.noSuchMethod(
            Invocation.getter(#library),
            returnValue: _FakeLibraryElement_5(
              this,
              Invocation.getter(#library),
            ),
            returnValueForMissingStub: _FakeLibraryElement_5(
              this,
              Invocation.getter(#library),
            ),
          )
          as _i2.LibraryElement);

  @override
  _i2.LibraryElement get library2 =>
      (super.noSuchMethod(
            Invocation.getter(#library2),
            returnValue: _FakeLibraryElement_5(
              this,
              Invocation.getter(#library2),
            ),
            returnValueForMissingStub: _FakeLibraryElement_5(
              this,
              Invocation.getter(#library2),
            ),
          )
          as _i2.LibraryElement);

  @override
  List<_i2.TypeParameterElement> get typeParameters =>
      (super.noSuchMethod(
            Invocation.getter(#typeParameters),
            returnValue: <_i2.TypeParameterElement>[],
            returnValueForMissingStub: <_i2.TypeParameterElement>[],
          )
          as List<_i2.TypeParameterElement>);

  @override
  List<_i2.TypeParameterElement> get typeParameters2 =>
      (super.noSuchMethod(
            Invocation.getter(#typeParameters2),
            returnValue: <_i2.TypeParameterElement>[],
            returnValueForMissingStub: <_i2.TypeParameterElement>[],
          )
          as List<_i2.TypeParameterElement>);

  @override
  List<_i2.Element> get children =>
      (super.noSuchMethod(
            Invocation.getter(#children),
            returnValue: <_i2.Element>[],
            returnValueForMissingStub: <_i2.Element>[],
          )
          as List<_i2.Element>);

  @override
  List<_i2.Element> get children2 =>
      (super.noSuchMethod(
            Invocation.getter(#children2),
            returnValue: <_i2.Element>[],
            returnValueForMissingStub: <_i2.Element>[],
          )
          as List<_i2.Element>);

  @override
  String get displayName =>
      (super.noSuchMethod(
            Invocation.getter(#displayName),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#displayName),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.getter(#displayName),
            ),
          )
          as String);

  @override
  int get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  bool get isPrivate =>
      (super.noSuchMethod(
            Invocation.getter(#isPrivate),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isPublic =>
      (super.noSuchMethod(
            Invocation.getter(#isPublic),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isSynthetic =>
      (super.noSuchMethod(
            Invocation.getter(#isSynthetic),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i2.ElementKind get kind =>
      (super.noSuchMethod(
            Invocation.getter(#kind),
            returnValue: _FakeElementKind_6(this, Invocation.getter(#kind)),
            returnValueForMissingStub: _FakeElementKind_6(
              this,
              Invocation.getter(#kind),
            ),
          )
          as _i2.ElementKind);

  @override
  _i2.Metadata get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: _FakeMetadata_7(this, Invocation.getter(#metadata)),
            returnValueForMissingStub: _FakeMetadata_7(
              this,
              Invocation.getter(#metadata),
            ),
          )
          as _i2.Metadata);

  @override
  _i2.Element get nonSynthetic =>
      (super.noSuchMethod(
            Invocation.getter(#nonSynthetic),
            returnValue: _FakeElement_8(this, Invocation.getter(#nonSynthetic)),
            returnValueForMissingStub: _FakeElement_8(
              this,
              Invocation.getter(#nonSynthetic),
            ),
          )
          as _i2.Element);

  @override
  _i2.Element get nonSynthetic2 =>
      (super.noSuchMethod(
            Invocation.getter(#nonSynthetic2),
            returnValue: _FakeElement_8(
              this,
              Invocation.getter(#nonSynthetic2),
            ),
            returnValueForMissingStub: _FakeElement_8(
              this,
              Invocation.getter(#nonSynthetic2),
            ),
          )
          as _i2.Element);

  @override
  _i2.Metadata get metadata2 =>
      (super.noSuchMethod(
            Invocation.getter(#metadata2),
            returnValue: _FakeMetadata_7(this, Invocation.getter(#metadata2)),
            returnValueForMissingStub: _FakeMetadata_7(
              this,
              Invocation.getter(#metadata2),
            ),
          )
          as _i2.Metadata);

  @override
  T? accept<T>(_i2.ElementVisitor2<T>? visitor) =>
      (super.noSuchMethod(
            Invocation.method(#accept, [visitor]),
            returnValueForMissingStub: null,
          )
          as T?);

  @override
  T? accept2<T>(_i2.ElementVisitor2<T>? visitor) =>
      (super.noSuchMethod(
            Invocation.method(#accept2, [visitor]),
            returnValueForMissingStub: null,
          )
          as T?);

  @override
  String displayString({
    bool? multiline = false,
    bool? preferTypeAlias = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#displayString, [], {
              #multiline: multiline,
              #preferTypeAlias: preferTypeAlias,
            }),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#displayString, [], {
                #multiline: multiline,
                #preferTypeAlias: preferTypeAlias,
              }),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.method(#displayString, [], {
                #multiline: multiline,
                #preferTypeAlias: preferTypeAlias,
              }),
            ),
          )
          as String);

  @override
  String displayString2({
    bool? multiline = false,
    bool? preferTypeAlias = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#displayString2, [], {
              #multiline: multiline,
              #preferTypeAlias: preferTypeAlias,
            }),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#displayString2, [], {
                #multiline: multiline,
                #preferTypeAlias: preferTypeAlias,
              }),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.method(#displayString2, [], {
                #multiline: multiline,
                #preferTypeAlias: preferTypeAlias,
              }),
            ),
          )
          as String);

  @override
  String getExtendedDisplayName({String? shortName}) =>
      (super.noSuchMethod(
            Invocation.method(#getExtendedDisplayName, [], {
              #shortName: shortName,
            }),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#getExtendedDisplayName, [], {
                #shortName: shortName,
              }),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.method(#getExtendedDisplayName, [], {
                #shortName: shortName,
              }),
            ),
          )
          as String);

  @override
  String getExtendedDisplayName2({String? shortName}) =>
      (super.noSuchMethod(
            Invocation.method(#getExtendedDisplayName2, [], {
              #shortName: shortName,
            }),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#getExtendedDisplayName2, [], {
                #shortName: shortName,
              }),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.method(#getExtendedDisplayName2, [], {
                #shortName: shortName,
              }),
            ),
          )
          as String);

  @override
  bool isAccessibleIn(_i2.LibraryElement? library) =>
      (super.noSuchMethod(
            Invocation.method(#isAccessibleIn, [library]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool isAccessibleIn2(_i2.LibraryElement? library) =>
      (super.noSuchMethod(
            Invocation.method(#isAccessibleIn2, [library]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i2.Element? thisOrAncestorMatching(bool Function(_i2.Element)? predicate) =>
      (super.noSuchMethod(
            Invocation.method(#thisOrAncestorMatching, [predicate]),
            returnValueForMissingStub: null,
          )
          as _i2.Element?);

  @override
  _i2.Element? thisOrAncestorMatching2(bool Function(_i2.Element)? predicate) =>
      (super.noSuchMethod(
            Invocation.method(#thisOrAncestorMatching2, [predicate]),
            returnValueForMissingStub: null,
          )
          as _i2.Element?);

  @override
  void visitChildren<T>(_i2.ElementVisitor2<T>? visitor) => super.noSuchMethod(
    Invocation.method(#visitChildren, [visitor]),
    returnValueForMissingStub: null,
  );

  @override
  void visitChildren2<T>(_i2.ElementVisitor2<T>? visitor) => super.noSuchMethod(
    Invocation.method(#visitChildren2, [visitor]),
    returnValueForMissingStub: null,
  );
}
