// Automatic schema type inference
// ignore_for_file: specify_nonobvious_property_types

import 'package:source_gen_test/annotations.dart';
import 'package:zodart/zodart.dart';

import '_helper_types.dart';

part 'goldens/pretype_new_class.dart';

// **************************************************************************
// Record test
// **************************************************************************

@ShouldGenerate('\n')
@ZodArt.withRecord(outputRecordType: OutputRecord)
abstract class R {
  static final schema = allTypesSchemaDef;
}

// **************************************************************************
// Existing class test
// **************************************************************************

@ShouldGenerate('\n')
@ZodArt.withExistingClass(outputClassType: OutputClass)
abstract class E {
  static final schema = allTypesSchemaDef;
}

// **************************************************************************
// New class test
// **************************************************************************

/// Helper mixin for [NewClass] (normally generated by ZodArt generator)
mixin _N {}

@ShouldGenerateFile(
  'goldens/pretype_new_class.dart',
  partOfCurrent: true,
)
@ZodArt.generateNewClass(outputClassName: 'NewClass')
abstract class N {
  static final schema = allTypesSchemaDef;
}
