// example file
// ignore_for_file: specify_nonobvious_property_types, avoid_print

import 'package:zodart/zodart.dart';

part 'cross_field_validation.zodart.dart';
part 'cross_field_validation.zodart.type.dart';

/// Validates that validTo is either null or is not before validFrom.
///
/// Autogenerated [UserSchemaFieldAccessor] provides rock-solid type-safety.
SuperRefinerErrorRes? validateFromTo(UserSchemaFieldAccessor values) {
  final validTo = values.validTo;
  if (validTo == null || !values.validFrom.isAfter(validTo)) {
    return null;
  }

  return (
    // Creates a customizable issue and attaches it to `validFrom`,
    // allowing UIs to highlight the source field.
    ZIssue.custom(
      message: 'Valid from cannot be later than valid to.',
      rawPath: ZPath.property(UserSchema.z.props.validFrom.name),
    ),
    others: [],
  );
}

/// User schema with all the crossFieldValidators included automatically
@ZodArt.generateNewClass(outputClassName: 'User', crossFieldValidators: [validateFromTo])
abstract class UserSchema {
  static final schema = (
    name: ZString().max(5),
    validFrom: ZDateTime(),
    validTo: ZDateTime().nullable(),
  );

  static const z = _UserSchemaUtils();
  static final ZObject<User> zObject = z.zObject;
}

void main() {
  // Cross-field validator output is obtained,
  // even if other fields failed the validations.
  UserSchema.zObject
      .parse({
        'name': 'INVALID NAME',
        'validFrom': DateTime(2025, 12, 24),
        'validTo': DateTime(2025, 12, 22),
      })
      .match(
        (issues) => print('Error:\n${issues.localizedSummary}'),
        (user) => print('Success: $user'),
      );
}
