name: Release

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  upload-to-codecov:
    name: Upload data to Codecov
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Install dependencies
        run: dart pub get

      - name: Activate coverage
        run: dart pub global activate coverage

      - name: Run tests with coverage
        run: dart pub global run coverage:test_with_coverage

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: zzundalek/zodart
